version: '3'

services:
  node_app: 
    build:
      context: node
    tty: true
    container_name: node_app
    networks:
      - nodenet
    volumes:
      - ./node:/usr/src/app
    depends_on:
      - db
    
  nginx: 
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: jmar33/nginx:prod
    container_name: nginx
    networks:
      - nodenet
    ports:
      - "8080:80"
    depends_on:
      - node_app

  db: 
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - nodenet

networks:
  nodenet:
    driver: bridge